project:
  type: website
  output-dir: docs

website:
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/geopanda1
      - text: "{{< bi gitlab >}}"
        href: https://git.uibk.ac.at/users/c716826/contributed

    left:
      - text: "Posts"
        href: index.qmd
      - text: "Code snippets"
        href: code-snippets.qmd

  sidebar:
    - title: "Tutorials"
      style: "docked"
      background: light
      collapse-level: 1
      sort: false
      contents:
        - section: Xarray
          contents:
            - code-snippets/xarray/util.qmd
            - code-snippets/xarray/00_rf_predict_map_blocks.ipynb
            - code-snippets/xarray/01_rf_predict_apply_ufunc.ipynb
            - code-snippets/xarray/02_resample_custom_func.ipynb
            - code-snippets/xarray/03_resampling_xr_reproject.ipynb
            - code-snippets/xarray/04_geotiff-to-xarray.ipynb
        - section: Pandas
          contents: 
            - code-snippets/pandas/00_groupyby-agg.qmd
        - section: Linux | Misc
          contents:
            - code-snippets/linux/apt.qmd
        - section: Data download
          contents:
            - code-snippets/data-download/00_download_s2_stac_asset.ipynb
            - code-snippets/data-download/01_download_s2_odc-stac.ipynb
            - code-snippets/data-download/02_download_s2_stackstac.ipynb
        - section: Dask
          contents:
            - code-snippets/dask/00_local_cluster.ipynb
        - section: Sqlalchemy
          contents:
            - code-snippets/sqlalchemy/00_relations.ipynb
            - code-snippets/sqlalchemy/01_views.ipynb
        - section: Joblib
          contents:
            - code-snippets/joblib/00_parallel_everything.ipynb
        - section: Requests
          contents:
            - code-snippets/requests/00_get_request.ipynb


format:
  html:
    theme: [simplex, styles.scss]
    linkcolor: grey




