project:
  type: website
  output-dir: docs

website:
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
    left:
      - text: "Posts"
        href: index.qmd
      - text: "Code snippets"
        href: code-snippets.qmd

  sidebar:
    - title: "Tutorials"
      style: "docked"
      background: light
      sort: false
      contents: 
        - section: Xarray
          contents:
            - code-snippets/xarray/00_rf_predict_map_blocks.ipynb
            - code-snippets/xarray/01_rf_predict_apply_ufunc.ipynb
            - code-snippets/xarray/02_resample_custom_func.ipynb
            - code-snippets/xarray/03_resampling_rioxarray.ipynb
            - code-snippets/xarray/04_resampling_xr_reproject.ipynb
        - section: Dask
          contents: 
            - code-snippets/dask/00_local_cluster.ipynb
        - section: Sqlalchemy
          contents: 
            - code-snippets/sqlalchemy/00_relations.ipynb
            - code-snippets/sqlalchemy/01_views.ipynb
        - section: Joblib
          contents: 
            - code-snippets/joblib/00_parallel_everything.ipynb
        - section: Requests
          contents: 
            - code-snippets/requests/00_get_request.ipynb
        

format:
  html:
    theme: simplex
    css: styles.css



